### ISSUE TITLE
openrail license

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/imagen-pytorch#216]
just wondering what people's thoughts are if i start migrating my repositories over to the [OpenRail](https://huggingface.co/blog/open_rail) license. all of my repositories are MIT licensed currently

yay or nay?

**Comment by deepglugs** [comment]
MIT is good.

**Comment by SappieKonig** [comment]
Does that make sense when not providing a model with the repository?

**Comment by lucidrains** [comment]
> Does OpenRAIL make sense when not providing a model with the repository?

Yup, there's one for data, model, source code. Here I am concerned with OpenRAIL-S

**Comment by lucidrains** [comment]
Here's more detail https://www.licenses.ai/blog/2022/8/18/naming-convention-of-responsible-ai-licenses I will probably switch over  next week unless there is a lot of good arguments why not

**Comment by lucidrains** [comment]
![Screenshot from 2022-09-10 10-31-58](https://user-images.githubusercontent.com/108653/189495065-434c5c0e-894b-4932-8634-0540e358136d.png)

**Comment by albertz** [comment]
What is the difference to MIT or others? Is there any? E.g. is commercial use of the code allowed? Is there anything not allowed which was allowed before?

Is it compatible with other MIT-licensed software? Or other BSD/Apache/whatever licenced software?
If this is unknown yet, I assume it is not compatible, which would be quite a big argument against using it.

**Comment by Mut1nyJD** [comment]
RAIL on paper is a nice concept but lets face in reality it it is pretty much unenforceable there is no way you can control that it is just used for given usage-restriction. 

I am not even sure where the responsibilities lies in this case?
At least with MIT you basically freed yourself from any responsibility (even though it probably will not uphold against new EU regulation that might be coming for Open Source) 

And so far what is completely unclear to me is who or what defines those usage-restrictions in the first place?

**Comment by lucidrains** [comment]
@Mut1nyJD yea i understand it is unenforceable, but i am one to still believe in affirmation. just as the hippocratic oath doesn't prevent physicians from being malignant individuals.

**Comment by lucidrains** [comment]
@Mut1nyJD yea i understand it is unenforceable, but i am one to still believe in affirmations (just as the hippocratic oath doesn't prevent physicians from being malignant individuals.)

**Comment by lucidrains** [comment]
> What is the difference to MIT or others? Is there any? E.g. is commercial use of the code allowed? Is there anything not allowed which was allowed before?
> 
> Is it compatible with other MIT-licensed software? Or other BSD/Apache/whatever licenced software? If this is unknown yet, I assume it is not compatible, which would be quite a big argument against using it.

no there will be no commercial restrictions

**Comment by Nodja** [comment]
Which version of the license are you planning to implement? Cause that to me makes a big difference. If it's the original version as defined [here](https://www.licenses.ai/source-code-license) then I'm against it. The obvious point being that we'd have to watermark photorealistic images as being AI generated even if they were only involved partially in the creative pipeline, which to me is silly and overbearing. If it's StableDiffusion's [CreativeML variant](https://github.com/CompVis/stable-diffusion/blob/69ae4b35e0a0f6ee1af8bb9a5d0016ccb27e36dc/LICENSE) then I'm fine with it as it basically boils down to "don't use the model for evil".

Regardless of license you pick you should be aware than neither version complies with the Open Source Definition document that is used internationally to define if software should be considered open source (it's the standard used by governments all over the world), much less the more strict Free Software definition that the FSF uses, so that might be a big deal if you care to call your software open source and/or Free Software. Despite the name of the license containing the word "open" in it, the openrail licenses are open source in spirit but they're not by official definition, and you'll definitely get some people bitching about it eventually if any of your repos become "mainstream popular".

Personally I'd stick with the MIT license, as a user/contributor I wouldn't mind the CreativeML variant, but would "jump ship" if the official version of the license was adopted.

**Comment by lucidrains** [comment]
@Nodja yup, the creative ML variant is what i wish for the repository, a simple positive affirmation

does anyone else object to that?

**Comment by ajbouh** [comment]
IMHO OpenRail feels like an open-ended liability because of its ambiguity and openness to interpretation.

Some examples of uncertainty created by OpenRail:
- What license should a dataset that's been deduped, cleaned or audited with an OpenRail model have? Does that license affect the downstream models that use the dataset?
- What license should a distillation or student model have if an OpenRail model is used as a teacher? Do you have to re-distill a model each time any upstream or teacher model is released?
- If an OpenRail model is used to generate a prompt for another model, what licenses apply to those responses? If OptFormer were licensed with OpenRail, would the same restrictions apply to models trained with the suggested hyperparameters?
- If an OpenRail checkpoint is used to validate (but not train) an existing model, does the OpenRail license extend to the validated model?

I think until MIT is demonstrated to have a specific flaw, OpenRail will probably fragment the ecosystem and generally limit both adoption and collaboration.

A few years ago the author of JSHint wrote up some notes on the choice to remove "The Software shall be used for Good, not Evil." from the JSHint license. The requirement started with obviously good intentions, but he believed it was worth spending years of effort to relicense the project to remove it.

Here's an excerpt from https://mikepennisi.com/blog/2020/jshint-watching-the-ship-sink/

> JSHint was partly licensed under [the JSON license](https://www.gnu.org/licenses/license-list.html#JSON). It is nearly identical to the widely-used MIT Expat license, but it includes one additional clause:
>
> > The Software shall be used for Good, not Evil.
>
> Because of this clause, folks who respect the practice of software licensing simply could not use JSHint.
>
> If you’re not versed in legal matters, that probably seems like an odd restriction. By rejecting JSHint, are people admitting that they want to do evil? And is that clause actually enforceable, anyway?
>
> The answer to the second question is “no,” and that helps answer the first question. Legally-conscious objectors aren’t betraying their own dastardly motivations; they’re refusing to enter into an ambiguous contract. Put differently: they’re not saying, “I’m an evildoer,” they’re saying, “I don’t understand what you want.” This consideration disqualified JSHint from inclusion in all sorts of contexts.
>
> ...

**Comment by lucidrains** [comment]
> 

oh thanks for this.. i'll review this tonight

**Comment by lucidrains** [comment]
@ajbouh Hey Adam 👋 thanks for weighing in

That is an interesting case study and I'll do more research on it next week. I think artificial intelligence software is in a different ballpark than a linter though.

**Comment by ajbouh** [comment]
Yes! Obviously a different ballpark. :)

My big takeaways from JSHint are:
1. a license can create an impedance mismatch between creators/contributors and the rest of the ecosystem
2. an ambiguous license is easily interpreted as a liability
3. a conservative choice in licensing makes more sense if relicensing is painful or expensive

(1) will become clear with time, (2) might improve with future iterations of OpenRail, and (3) might come down to economics

Also, after re-reading the thread above, I see that you're talking specifically about the S variant.

IANAL but this might mean that your models won't ship in linux distributions, browsers, phones, cameras, hardware, or any other contexts that lack mechanisms needed for behavior-use restrictions.

**Comment by lucidrains** [comment]
yeah true

I'll sleep on it tonight and come to a decision tomorrow evening

thanks all!

**Comment by lucidrains** [comment]
will keep with MIT license for now

**Comment by Aspie96** [comment]
I am not a contributor, so I have no "vote" on this. These are just my 2 cents (and not legal advice!).

First, something true regardless of what you choose: if you switch from the MIT license to any other license and you have received contributions under the MIT license, you must preserve the text of the MIT license intact. Probably you already know it, but I've seen some projects moving towards "ethical licenses" and failing to do this.

That said, I strongly suggest that you continue to use the MIT license, and avoid any OpenRAIL license, or any other "ethical license", for several reasons:
1) Any ethical restriction that you may apply to any project only applies to those parties not rich enough to build an alternative (or hiring someone to do so). Those, companies or individuals, who are rich or powerful are not restricted in any way in their endeavors, good or evil. Them using other tools, rather than yours, is no issue whatsoever for them, nor a benefit for you.
2) The cool thing about restrictions such as distribution of copyright notices or copyleft (although MIT is not copyleft) is not that they prevent people from distributing the software unless they comply with such restrictions (although that is the legal hook). Rather, such clauses are successful in actually getting people to comply with them, since users are willing to pay that price. In essence, some software actually is free software thanks to copyleft licenses, from parties that would otherwise have used proprietary licenses. And a lot of software mentions authors thanks to the MIT license. In the case of an ethical license, you cannot have this kind of success: none would decide to use your software more ethically because of the license, but rather they may not use it at all, which would not be considered as a success for any other kind of license.
3) There is a good argument to be made that governments should not use software under proprietary licenses, including ethical ones. The reason is that a democratic government should use its own legal system to determine the scope of its actions, aligning with the political ideas of the electors, not with the restrictions of the authors of software they happen to be dependent upon. I don't think you make software specifically for governments, but government agencies, especially in academia, are potential users, direct or indirect, of your software.
4) Imposing ethical restrictions on software breaks cooperation between politically different parties. Moreover, it's far from clear what restrictions could or should be added to those already present.
5) Ethical licenses often forbid behaviours which are already illegal. It's hard to argue that the penalty for such acts, many of which are criminal, should be raised by exactly a copyright violation. Indeed, it seems almost absurd. Lawful behaviors forbidden by ethical licenses are often behaviors the license author simply subjectively despise, around topics they value more than equally important ones.

When it comes to pretrained weights, there is the added issue that restrictions, of any kind, rely on trained models being copyrightable. Whether they are and whether they should be are two (different) open questions, the former legal, the second ideological. I suggest that the answer is most likely to be no for both, something outside the scope of this comment.

I will also link to some articles you probably already know fully well, but some other readers might not:
- https://perens.com/2019/09/23/sorry-ms-ehmke-the-hippocratic-license-cant-work/
- https://www.gnu.org/philosophy/programs-must-not-limit-freedom-to-run.html

Those arguments apply in general for any ethical license. Specifically about the text of the OpenRAIL license, however, I have to say that it goes beyond just forbidding "unethical" acts, granting a very strong level of control to the author (for instance, by forcing users to upgrade to the latest version, something very reasonable and good users may not want to do, and indeed a clause most users should reject). In addition, some parts of the text of the license seem rather hard to interpret to me (such as "You are accountable for the Output you generate and its subsequent uses": to whom, in what way? Or "No use of the output can contravene any provision as stated in the License"). The only case in which I would ever use something under this license, or advise someone else to do so, is if the situation at hand is clearly an exception to copyright law, or falls under fair use (depending on jurisdiction), so that the text of the license can simply be fully ignored altogether.

Lastly, it's important to notice that ethical licenses, such as the OpenRAIL licenses, are not free or open source licenses, not even in the spirit, while the MIT license absolutely is. This is not an argument against using ethical licenses, at all, just something that I'll point out for clarity.

Personally, I am in open and full opposition to the ethical licensing model, and believe the open source licensing model to be by far superior. However, I also believe that it's the right to software authors to license things however they wish, including of course you. The choice is yours, and whatever you decide is your right.

I actually think that you making open source alternatives to ethically licensed AI models would be as valuable of a contribution to the community as what you have been doing so far (and something I encourage you to do).

We should fight injustices in the world, but not everything done with that purpose is optimal, or even beneficial, and restrictions trough software licensing are most definitely not. Copyright licenses are not the right place for "affirmations"; blogs are. When it comes to legal documents, the legal and practical consequences are what matters the most.

But if, instead, you decide to switch away from the MIT license, you should at least inform your sponsors, and give them the time to decide what to do about it (since your sponsorship page says "with a liberal license", which OpenRAILS is arguably not).

(Finally, I admire what you've done so far and everything you have contributed to the open source world).

**Comment by ProGamerGov** [comment]
> RAIL on paper is a nice concept but lets face in reality it it is pretty much unenforceable there is no way you can control that it is just used for given usage-restriction. 
> 
> I am not even sure where the responsibilities lies in this case?
> At least with MIT you basically freed yourself from any responsibility (even though it probably will not uphold against new EU regulation that might be coming for Open Source) 

Do you have any sources for the MIT license becoming illegal for AI projects? I know the upcoming EU legislative proposal is pretty hostile to open source AI, but what part of it attack MIT?

**Comment by Aspie96** [comment]
I think they mean the disclaimer will do no good in the EU, not that the MIT license will literally be illegal.
