### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by inFACTfinder** [lucidrains/imagen-pytorch#30]
Hi there! Love the project just needing a little help with installation of a package.
`    
from imagen_pytorch.t5 import t5_encode_text, get_encoded_dim, DEFAULT_T5_NAME
ModuleNotFoundError: No module named 'imagen_pytorch.t5'; 'imagen_pytorch' is not a package
`

Sorry if I'm being stupid or if this is the wrong place to ask.

**Comment by lucidrains** [comment]
@inFACTfinder `pip install imagen-pytorch` should take care of everything and the dependencies

**Comment by inFACTfinder** [comment]
Hi. Thank you for replying. This project is amazing! I tried this but unfortunately it doesn't work (pip3 as well). The full error when I run __init__.py is 
`Traceback (most recent call last):
  File "/Users/USER/Documents/AI/imagen-pytorch-main/imagen_pytorch/test.py", line 2, in <module>
    from imagen_pytorch import Unet, Imagen
  File "/Users/USER/Documents/AI/imagen-pytorch-main/imagen_pytorch/imagen_pytorch.py", line 23, in <module>
    from imagen_pytorch.t5 import t5_encode_text, get_encoded_dim, DEFAULT_T5_NAME
ModuleNotFoundError: No module named 'imagen_pytorch.t5'; 'imagen_pytorch' is not a package`

**Comment by lucidrains** [comment]
@inFACTfinder i'll think about docker or podman going forward so we don't have this issue

**Comment by VladoPortos** [comment]
@lucidrains I would recommend COG as base, its simple to work with and help a lot regarding ML / AI https://github.com/replicate/cog

**Comment by lucidrains** [comment]
> @lucidrains I would recommend COG as base, its simple to work with and help a lot regarding ML / AI https://github.com/replicate/cog

thank you! that looks like an excellent project :)

**Comment by SethKitchen** [comment]
So if I download LAION dataset what to inset for

text_embeds = torch.randn(64, 256, 1024).cuda()
text_masks = torch.ones(64, 256).bool().cuda()
images = torch.randn(64, 3, 256, 256).cuda()


Can you link to example where these are loaded from a dataset?

**Comment by Mimocro** [comment]
@SethKitchen check colab notebook from https://github.com/lucidrains/imagen-pytorch/issues/24 and replace get image tensor function to [this](https://github.com/lucidrains/imagen-pytorch/blob/main/imagen_pytorch/data.py#L18) 
https://colab.research.google.com/drive/1zVFcWU7REDmQXKs5gBNAu7kdPEAgG5wy?usp=sharing

**Comment by xuanloc088** [comment]
> Hi. Thank you for replying. This project is amazing! I tried this but unfortunately it doesn't work (pip3 as well). The full error when I run **init**.py is `Traceback (most recent call last): File "/Users/USER/Documents/AI/imagen-pytorch-main/imagen_pytorch/test.py", line 2, in <module> from imagen_pytorch import Unet, Imagen File "/Users/USER/Documents/AI/imagen-pytorch-main/imagen_pytorch/imagen_pytorch.py", line 23, in <module> from imagen_pytorch.t5 import t5_encode_text, get_encoded_dim, DEFAULT_T5_NAME ModuleNotFoundError: No module named 'imagen_pytorch.t5'; 'imagen_pytorch' is not a package`

Dear friend, I also have the same problem with you, I don't know whether you solved it or not ? If you do, please give me an instruction for it, thank you very much

**Comment by 2kinto** [comment]
No module named 'imagen_pytorch.t5'; 'imagen_pytorch' is not a package  Same problem T_T

**Comment by DataDetactive** [comment]
Hi @2kinto ,

I hope that you figured out the solution of the problem. If you not. let me explain something maybe it could help you to solve the problem. so first  you should noticed that the folder name have the same name as  the script <"imagen_pytorch">. So I think you try to run a script inside the folder<"imagen_pytorch">. That will raise a problem because the error said I do not know any thing about class or file called t5. and the reason for that is the author made a train script outside the folder so when I need to get a file or something out side the folder I will write like that <"from imagen_pytorch.t5"> the first part before the dot is the folder name and the second part after the dot is the file you need to get the classes from or the functions. 
So If you want to solve this problem probably you should make a train script and try to test whatever modification you did in the model. I hope that you understand me.
